---
title: "Reguły asocjacyjne dla jadalnych grzybów"
author: "Ludwik Przyrowski"
date: "7 maja 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```


## Wstęp
Celem ćwiczenia jest znalezienie reguł asocjacyjnych dla zbioru opisu grzybów. W ćwiczeniu posłużono się zbiorem [Mushroom Data Set](https://archive.ics.uci.edu/ml/datasets/Mushroom) zawierający opisy fizycznych cech grzybów i ich klasyfikację na jadalne i nie jadalne.  

Jako, że chcemy zapamiętać reguły na jadalne grzyby, reguły te nie mogą być za długie. Stąd wynika ograniczenie na długość reguły.

Chcemy też być pewni że znaleziony grzyb na pewno nie będzie trujący. Stąd warunek na pewność wynoszącą 100%.

Ważne jest aby podczas wyjścia na spacer znalezeinie grzyba było prawdopodobne musimy założyć odpowiednio wysokie wsparcie.


## Algorytm

użyte biblioteki
```{R, message=F}
library(arules) #reguły asocjacyjne
library(arulesViz) # wizualizacja reguł

```
zbiór mushroom
```{R}
data("Mushroom")
summary(Mushroom)
#inspect(head(Mushroom))
```

szukanie reguł assocjacyjnych
```{R}
rulesWithRHS <- apriori(Mushroom, parameter = list(support=0.3, confidence = 1.0, minlen =1), 
                        appearance = list(rhs = c("Class=edible"), default="lhs"))
inspect(head(sort(rulesWithRHS, by="support"),10))

```

## Podsumowanie
W wyniku działania algorytmu uzyskaliśmy listę reguł asocjacyjnych dla jadalnych grzybów posortowaną po wsparciu. Lista ta jest łatwa do zapamiętania gdyż jest niedługa (10 pozycji) oraz zawiera małą ilość cech do zapamiętania (od 3 do 4). Użycie takiej listy może być pomocne w decyzji na grzybobraniu.